name = "Fermi"
uuid = "9237668d-08c8-4784-b8dd-383aa52fcf74"
authors = ["gustavojra <gustavo.aroeira@gmail.com>"]
version = "0.2.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
TBLIS = "48530278-0828-4a49-9772-0f3830dfa1e9"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Formatting = "^0.4.1"
Memoize = "0.4"
Suppressor = "0.2"
TBLIS = "^0.2.0"
TensorOperations = "^3.0.0"
julia = "^1.5"
